### PR TITLE
removes gin related code as it is now redundant

### PR DESCRIPTION
**Pull request by cubixle**
This has been removed as no service uses it anymore and it is causing compatibility issues when running ```glide install``` due to a mismatch in protobuf versions.

### CODE REVIEW

**Comment by cubixle** [comment]
Before merging we should keep a version of the current master branch for fallback. Reason being is although services no longer use this we may need to rollback to an older version at some point.

**Comment by pawmart** [comment]
@lukerodham  thats what tags are for and thats what hash in glide file is for right? isn't that good enough?

**Comment by pawmart** [comment]
added current branch as fixed release so we can refer to it if needed

**Review by pawmart — APPROVED** [review]

**Comment by cubixle** [comment]
Awesome, I'll merge the changes and create PR to master.

**Pull request merged**
